### ISSUE TITLE
Tutorial Please

### ISSUE THREAD

**Issue by KevinBRitter** [Adam1400/cs350#11]
Hi, great project.  I accidently became stuck on someone's capture page while trying to like their video.  When I tried to go back to the main page I tried to add a new picture then saw the home button there.  I did eventually notice the "Capture" header was a home button/ link but it took me a minute or two after looking at several other captures.

Will there be a home button added on every page, or icon next to the header, or even a new user guide?  
Thank you, again, it really is a nice app!

-Kevin

**Comment by Adam1400** [comment]
Great point Keven. I will add a home button to the pages that don't have one! I suppose I forgot to add the home button because I always just used the link in the top to get back. Had a bit of tunnel vision there. Thanks for the feedback!

**Comment by Adam1400** [comment]
Fixed, thanks again!
