### ISSUE TITLE
Like

### ISSUE THREAD

**Issue by sstrawmatt2** [Adam1400/cs350#15]
I think you guys did an awesome job. I really enjoyed how simple the app was. I was wondering if you guys would consider implementing user stories? Like on Instagram each user can put a story up. I know it's not really ideal but it would be a cool feature. Probably a lot harder than it seems. Overall though I think you guys knocked it out of the park.

**Comment by Adam1400** [comment]
Thanks Sean! That would be a cool feature but... It would take a lot of work to implement. Probably couldn't finish it in time. We'll see!
