### ISSUE TITLE
Limit picture size

### ISSUE THREAD

**Issue by ramosv** [Adam1400/cs350#16]
This website is really cool and it has a very simple and clean design. This isn't much of an issue but more of an personal opinion, I think there should be a limit on the size of a picture. Some of the images will not fit on my browser window. This only happens on my laptop, I access the website on my phone and it looks great. Maybe I should just get a bigger monitor.

**Comment by Adam1400** [comment]
I hear you, someone else mentioned this also. We do not compress the pictures, so what people upload is what you get. However, since now 2 people have mentioned this... I will apply some compression and scaling so the pictures fit better! Thank you for the feedback!

**Comment by Adam1400** [comment]
This has been fixed! Pictures should now scale better to fit your browser. Let me know if everything looks alright, and thanks for the feedback!
