### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by SProv7615** [Adam1400/cs350#5]
Overall, the website seems like it's well-designed. Three main, but minor, complaints: It's not completely obvious that the Capture at the top-middle is a link, and secondly, the zoom-in feature is honestly a bit... uh, frustrating while scrolling down the page if your cursor happens to be in the middle of the page. Maybe add a second-long delay? Lastly, the profile pictures do not seem like they really need to be able to be zoomed in on. Stretch goal of preventing that zoom-function there?

Anyways, good job guys, very professional and slick.

**Comment by Adam1400** [comment]
What's the issue though with the link at the top? As for the zoom feature I hear you. Creating a pause before it expands is a good idea though.  I wanted to stray away from having to use JavaScript on this project... so I didn't implement any fancy way of expanding the pic.... but.... a pause seems completely feasible in css alone. Thank you for that suggestion. How long do you think the pause should take? 

As for the profile pics, what zoom do you not like? The home page profile pic zoom or the detail page profile pic zoom?

**Comment by SProv7615** [comment]
I honestly think a pause should only take about a second or so. As for the
link at top, one of my group-mates had a moment where he literally asked,
"How do we get back without the back button." It was mostly in response to
his question. A pause probably should only take a second, maybe a second
and a half to work.

And as for the profile pictures, I guess it's mostly just a me-thing. While
I don't mind them, I never really care to see them expanded! I would say
that there's no issue with them expanding on people's profile pages,
considering it's their actual profile page, but the home page profile
picture zoom seems excessive in my highly opinionated opinion. :P
Regardless, again, good work on the site.

**Comment by Adam1400** [comment]
Good feedback, thank you!

**Comment by Adam1400** [comment]
Added these features. Thanks again.
