### ISSUE TITLE
like

### ISSUE THREAD

**Issue by Angel-V-Rivera** [Adam1400/cs350#6]
Is a little frustrating that when you try to like a post it takes you to the author profile and then you have to click the like again.

**Comment by Adam1400** [comment]
Yeah I hear you. I tried to make it like on the main page... but doing that made the page refresh and jump back to the top (witch I found more frustrating). So I picked the lesser of 2 evils. As I mentioned in the presentation, we would need to implement an axaj request to get the thing working how you'd expect... and that is a bit complex... probably couldn't finish that before class is over. If you have any references on how I might get it working though, LMK! Thanks!
