### ISSUE TITLE
Profile pictures

### ISSUE THREAD

**Issue by KiraMatchBox** [Adam1400/cs350#7]
The thumbnails for profile pictures squashes the image rather than cropping it. An interface that lets the user crop their photo to a circle when adding a profile picture would be neat. 
Super impressive overall! Well done

**Comment by Adam1400** [comment]
Yeah we were aware the pics squished instead of cropped... we didn't want to crop the raw pic, just incase we wanted to use the full thing for another feature. So this was a design decision. I'll see if I can crop the pic with css though. Thanks for the feedback!

**Comment by Adam1400** [comment]
Pictures are now scaled better. Thanks for the feedback!
