### ISSUE TITLE
Wrong Timestamp When Posting/Liking Issue

### ISSUE THREAD

**Issue by thom1664** [Adam1400/cs350#9]
First of all awesome job! This application is very simple and easy to use from a user perspective. I did notice however when creating a post it gave the time of posting at around 7:31pm when it was actually 12:31pm. I also noticed that when logged out and attempting to like a post; I do get redirected to the login page however, when I login it gives me an error (included in screenshot). Overall great work guys!!
<img width="944" alt="Screen Shot 2020-11-18 at 12 51 17 PM" src="https://user-images.githubusercontent.com/55003411/99580522-26aac300-29a5-11eb-9da9-9758310f555c.png">

**Comment by Adam1400** [comment]
Yeah, I was already aware the time is incorrect... Still working on a fix. As for the login issue, I appreciate you bringing that to my attention I'll get to work on fixing that! Good feedback thanks!

**Comment by Adam1400** [comment]
Got these problems fixed, thank you for the heads up!
